### ISSUE TITLE
Transforms to add to the augmentation pipeline

### ISSUE THREAD

**Issue by stephandooper** [DIAGNijmegen/lightstream#3]
- [x]  Pad tile to delta
- [x]  Crop or pad (formerly pad_or_drop in psp)
- [ ]  limit_size()
   - random crop (if mask not available)
   - crop using mask (if mask available)
- [x] Brightness and contrast
- [x] Random 360 degrees rotations
- [x] Gaussian Blur
- [x] HSV jitter
- [x] Gaussian noise
- [x] Gamma
- [ ] Random tone curve
- [ ] Sharpen
```[tasklist]
### Tasks
```
